/* Tema: Bloqueo de Línea y Equipo + Reposición de Chip
   Fuentes: Bloqueo de Línea y Equipo Diagrama.xlsm, Reposición de Chip Diagrama.xlsm */
window.TEMAS = window.TEMAS || {};
window.TEMAS["bloqueo"] = {
  titulo: "Bloqueo de Línea y Equipo / Reposición de Chip",
  preguntas: [

  { q:"¿Cuáles son los motivos válidos para un bloqueo de línea y equipo a solicitud del cliente?",
    opciones:["Robo, hurto o pérdida","Deuda o falta de pago","Viaje al extranjero"],
    correcta:"Robo, hurto o pérdida",
    exp:"El proceso detalla «bloquear la línea y equipo a solicitud del cliente por motivo de robo / hurto o pérdida». Tipo de bloqueo: Robo / Pérdida / Hurto.",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Por normativa de OSIPTEL, ¿qué se bloquea siempre?",
    opciones:["La línea y el último equipo asociado (está prohibido bloquear solo línea o solo equipo)","Solo la línea","Solo el equipo"],
    correcta:"La línea y el último equipo asociado (está prohibido bloquear solo línea o solo equipo)",
    exp:"«Informar que por normativa de OSIPTEL siempre se bloquea la línea y último equipo asociado (está prohibido bloquear sólo línea o sólo equipo)».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"¿Cuántas preguntas de seguridad debe responder correctamente el cliente para continuar con el bloqueo?",
    opciones:["3 preguntas","2 preguntas","5 preguntas"],
    correcta:"3 preguntas",
    exp:"«Realiza preguntas de seguridad; si el cliente responde 3 preguntas correctamente continúa con la operativa».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El 'Nro. de llamada entrante' de una línea MÓVIL debe registrarse con:",
    opciones:["9 dígitos","8 dígitos","7 dígitos"],
    correcta:"9 dígitos",
    exp:"«Si es una línea móvil, debe tener 9 dígitos». Si es fija, 8 dígitos (incluye el prefijo).",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El 'Nro. de llamada entrante' de una línea FIJA debe registrarse con:",
    opciones:["8 dígitos (incluye el prefijo)","9 dígitos","6 dígitos"],
    correcta:"8 dígitos (incluye el prefijo)",
    exp:"«Si es una línea fija, debe tener 8 dígitos (incluye el prefijo)».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Al concretar el bloqueo, ¿qué información es OBLIGATORIO brindar al cliente?",
    opciones:["Marca y modelo del equipo, el IMEI omitiendo el último dígito, y el código de bloqueo correlativo de SIAC Único","Solo el código de bloqueo","El IMEI completo y la dirección de la tienda"],
    correcta:"Marca y modelo del equipo, el IMEI omitiendo el último dígito, y el código de bloqueo correlativo de SIAC Único",
    exp:"«Obligatorio informar al cliente al bloquear: marca y modelo del equipo bloqueado; número de IMEI del equipo omitiendo el último dígito; el código de bloqueo correlativo que muestra el SIAC Único al finalizar».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Al informar el IMEI del equipo bloqueado, el asesor:",
    opciones:["Omite el último dígito e informa al cliente que se omite","Informa el IMEI completo","No informa el IMEI"],
    correcta:"Omite el último dígito e informa al cliente que se omite",
    exp:"«Número de IMEI del equipo omitiendo el último dígito (infórmale que se omite el último dígito)».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Tras el bloqueo, respecto al correo electrónico, el asesor debe:",
    opciones:["Preguntar y validar en SIAC Único si el correo es vigente","Ignorar el correo","Solo pedirlo si el cliente lo menciona"],
    correcta:"Preguntar y validar en SIAC Único si el correo es vigente",
    exp:"«¿Pregunta y valida en SIAC Único si el correo electrónico es vigente? (en el caso de empresas valida en el B02)».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"¿Cuándo puede el asesor actualizar el correo electrónico durante el bloqueo?",
    opciones:["Solo si llama el Titular o RRLL / Contacto Autorizado","Siempre, con cualquier persona","Nunca, solo en canal presencial"],
    correcta:"Solo si llama el Titular o RRLL / Contacto Autorizado",
    exp:"«Solo si llama el Titular o RRLL / Contacto Autorizado, actualiza el correo electrónico».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Como recomendación de valor tras un bloqueo por robo, el asesor debe recomendar:",
    opciones:["Bloquear las tarjetas de banca móvil y cambiar las contraseñas de las cuentas de correo","Comprar un equipo nuevo de inmediato","Presentar un reclamo"],
    correcta:"Bloquear las tarjetas de banca móvil y cambiar las contraseñas de las cuentas de correo",
    exp:"Información obligatoria (registre o no el bloqueo): «Recomienda el bloqueo de sus tarjetas de su banca móvil y el cambio de contraseñas en sus cuentas de correo».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Para aprobar una solicitud de reposición de chip por Mi Claro, es obligatorio que el cliente:",
    opciones:["Esté registrado en Mi Claro y cuente con contraseña única","Tenga un plan postpago","Tenga menos de 30 días de activación"],
    correcta:"Esté registrado en Mi Claro y cuente con contraseña única",
    exp:"«Reposición de Chip: recomienda que el cliente esté registrado en Mi Claro. Obligatorio contar con contraseña única para aprobar la solicitud de reposición de chip».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"En Persona Natural, ¿quién puede solicitar el bloqueo de línea y equipo?",
    opciones:["El titular o el usuario","Solo el titular","Cualquier persona"],
    correcta:"El titular o el usuario",
    exp:"«Valida los datos de quien está solicitando el bloqueo: Persona Natural: TITULAR o USUARIO».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"En Persona Jurídica, ¿quién puede solicitar el bloqueo?",
    opciones:["RRLL, Contacto Autorizado, Usuario o Tercero Autorizado","Solo el RRLL","Solo el usuario"],
    correcta:"RRLL, Contacto Autorizado, Usuario o Tercero Autorizado",
    exp:"«Persona Jurídica: RRLL, Contacto Autorizado, USUARIO o Tercero Autorizado».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Al seleccionar el tipo de bloqueo aparece una alerta obligatoria. ¿Cuál es?",
    opciones:["Es obligatorio realizar la validación de datos del titular de la línea","El equipo se bloqueará en 24 horas","El cliente debe pagar una tarifa"],
    correcta:"Es obligatorio realizar la validación de datos del titular de la línea",
    exp:"«Al seleccionar el tipo de bloqueo se muestra la alerta: 'Es obligatorio realizar la validación de datos del titular de la línea'».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El asesor debe validar si el cliente tiene tipificaciones de bloqueo NO concretado en SIAC Único. ¿Cuántas y en qué período?",
    opciones:["3 tipificaciones registradas el mismo día","5 tipificaciones en el mes","2 tipificaciones en la semana"],
    correcta:"3 tipificaciones registradas el mismo día",
    exp:"«Valida ¿si cliente cuenta con 3 tipificaciones de bloqueo NO concretado en SIAC Único, registradas el mismo día?».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El listado de equipos asociados a la línea muestra:",
    opciones:["Los 3 últimos equipos vinculados a la línea","Todos los equipos históricos","Solo el equipo actual"],
    correcta:"Los 3 últimos equipos vinculados a la línea",
    exp:"«Listado de equipos asociados a la línea: se muestra los 3 últimos equipos que están vinculados a la línea del cliente».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Antes de ejecutar el bloqueo, el asesor confirma obligatoriamente con el cliente:",
    opciones:["La marca y modelo del último equipo vinculado que se procederá a bloquear","El número de IMEI completo","El plazo de resolución del OSIPTEL"],
    correcta:"La marca y modelo del último equipo vinculado que se procederá a bloquear",
    exp:"«Confirma de manera obligatoria con el cliente la marca y modelo del último equipo vinculado que se procederá a bloquear».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El cliente NO está de acuerdo con bloquear el último equipo. ¿Qué opción se le brinda?",
    opciones:["Solicitar el bloqueo del IMEI vinculado anterior (informándole marca y modelo)","Bloquear ningún equipo","Bloquear todos los equipos de la cuenta"],
    correcta:"Solicitar el bloqueo del IMEI vinculado anterior (informándole marca y modelo)",
    exp:"«Si no está de acuerdo, brinda al cliente la opción de solicitar el bloqueo (IMEI vinculado anterior) informándole la marca y modelo de equipo».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el cliente persiste en no bloquear ni el último ni el anterior equipo, el asesor:",
    opciones:["Informa que por normativa se bloquea el último equipo asociado e indica que se acerque al canal presencial","Bloquea solo la línea","No realiza ningún bloqueo"],
    correcta:"Informa que por normativa se bloquea el último equipo asociado e indica que se acerque al canal presencial",
    exp:"«Si persiste: informa que por normativa se bloquea el último equipo asociado a la línea e indica que se acerque al canal presencial».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"En el campo 'Teléfono de referencia' se registra:",
    opciones:["Un número distinto al número que se desea bloquear","El mismo número que se bloquea","El número del asesor"],
    correcta:"Un número distinto al número que se desea bloquear",
    exp:"«Teléfono de referencia: se registra el N° de referencia distinto al número que desea bloquear».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"En el campo 'Notas' de la solicitud de bloqueo se agrega:",
    opciones:["El SN de la solicitud del cliente","La dirección del cliente","El código del equipo"],
    correcta:"El SN de la solicitud del cliente",
    exp:"«En notas se agrega la SN de la solicitud del cliente».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Tras dar clic en BLOQUEAR, ¿cuál es el tiempo de respuesta?",
    opciones:["Hasta 3 minutos","Inmediato","Hasta 24 horas"],
    correcta:"Hasta 3 minutos",
    exp:"«Solo una vez se da clic en BLOQUEAR, el tiempo de respuesta: hasta 3 min».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el bloqueo NO se ejecuta por error/rechazo, el asesor primero debe:",
    opciones:["Intentar corregir y registrar el bloqueo nuevamente en SIAC Único","Generar el caso manual de inmediato","Transferir a Reclamos"],
    correcta:"Intentar corregir y registrar el bloqueo nuevamente en SIAC Único",
    exp:"«El asesor debe intentar corregir y registrar el bloqueo nuevamente en SIAC Único» (revisar N° de teléfono de llamada entrante, tipo y N° de documento, sin espacios).",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el error de bloqueo persiste, el asesor:",
    opciones:["Genera el registro del caso manual, derivado a la cola BACK OFFICE ATC MÓVIL","Reinicia SIAC Único","Cierra la llamada"],
    correcta:"Genera el registro del caso manual, derivado a la cola BACK OFFICE ATC MÓVIL",
    exp:"«Si persiste debe generar el registro del caso manual» y se registra «derivado a la cola BACK OFFICE ATC MÓVIL».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Para clientes empresa, el caso manual de bloqueo se genera:",
    opciones:["En cada línea del cliente, no en el ID","Solo en el ID de la cuenta","Una sola vez para toda la cuenta"],
    correcta:"En cada línea del cliente, no en el ID",
    exp:"«Para los clientes empresas el caso se genera en cada línea del cliente, no en el ID».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Cuando se genera el caso manual por rechazo, ¿qué se informa al cliente sobre el plazo?",
    opciones:["Se validará el motivo de rechazo en un plazo máximo de 24 horas y se le comunicará el resultado","Que espere 10 días útiles","Que vuelva a llamar en 48 horas"],
    correcta:"Se validará el motivo de rechazo en un plazo máximo de 24 horas y se le comunicará el resultado",
    exp:"«Se va a realizar la validación del motivo de rechazo y se realiza en un plazo máximo de 24 horas, nos comunicaremos para brindarle el resultado y las acciones a seguir».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Después de generar el caso manual de bloqueo por rechazo, el asesor:",
    opciones:["No registra el caso nuevamente en SIAC Único","Registra un caso nuevo cada vez que el cliente llama","Escala a Reclamos"],
    correcta:"No registra el caso nuevamente en SIAC Único",
    exp:"«No registrar caso nuevamente en SIAC Único». El área de Back Office ATC Móvil coloca el seguimiento en las notas del caso hasta su cierre.",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Mensaje 'El equipo que intenta registrar ya existe y está asociado a la línea xxxx'. ¿Qué hace el asesor?",
    opciones:["Valida que el IMEI esté vinculado a la línea a bloquear y solicita a su supervisor que registre la eliminación del equipo","Bloquea la otra línea","Registra un cuestionamiento ante OSIPTEL"],
    correcta:"Valida que el IMEI esté vinculado a la línea a bloquear y solicita a su supervisor que registre la eliminación del equipo",
    exp:"«El asesor valida que el IMEI del equipo esté asociado-vinculado a la línea que desea bloquear. Solicita a su supervisor que registre la eliminación del equipo». Una vez registrado, procede con el bloqueo.",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el cliente NO menciona el motivo del bloqueo, el asesor:",
    opciones:["Consulta la causa real para proceder con el bloqueo de línea y equipo","Bloquea por robo por defecto","No realiza el bloqueo"],
    correcta:"Consulta la causa real para proceder con el bloqueo de línea y equipo",
    exp:"«Si cliente no menciona el motivo del bloqueo, se debe consultar la causa real, para proceder con el bloqueo de línea y equipo».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"La reposición de chip (físico o eSIM) se realiza:",
    opciones:["De forma presencial, ya que requiere verificación biométrica para evitar suplantaciones","Solo por teléfono","Automáticamente por Mi Claro App"],
    correcta:"De forma presencial, ya que requiere verificación biométrica para evitar suplantaciones",
    exp:"«La reposición de chip (físico o eSIM) se realiza de forma presencial a fin de evitar suplantaciones de identidad, ya que requiere la verificación biométrica».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"¿Cuál es el plazo para recuperar el chip (prepago y postpago)?",
    opciones:["Hasta 6 meses contado desde el día del bloqueo","Hasta 30 días","Hasta 1 año"],
    correcta:"Hasta 6 meses contado desde el día del bloqueo",
    exp:"«Plazo de atención (para recuperar chip): Prepago y Postpago: hasta 6 meses contado desde el día del bloqueo».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Realizada la reposición del chip, ¿cuándo se reactiva el servicio?",
    opciones:["En 1 hora, posterior a concretarse el pago","Inmediatamente","En 24 horas"],
    correcta:"En 1 hora, posterior a concretarse el pago",
    exp:"«Realizada la reposición del chip, la reactivación del servicio se realizará en 1 hora, posterior de concretarse el pago».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Para la reposición de chip en el módulo de atención, es requisito indispensable:",
    opciones:["Exhibir el Documento de Identidad de manera física","Llevar el equipo original","Presentar el último recibo pagado"],
    correcta:"Exhibir el Documento de Identidad de manera física",
    exp:"«Es requisito indispensable exhibir el Documento de Identidad de manera física en el módulo de atención».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Para la reposición de chip, la línea debe estar en estado:",
    opciones:["Activo, o suspendida por robo o pérdida","Solo Activo","Desactivo"],
    correcta:"Activo, o suspendida por robo o pérdida",
    exp:"«La línea debe estar en estado 'Activo', o suspendida por robo o perdida».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Si un TERCERO realiza la reposición de chip, debe presentar:",
    opciones:["Carta poder legalizada y, además, pasar la biometría / no biometría","Solo su DNI","Una autorización verbal del titular"],
    correcta:"Carta poder legalizada y, además, pasar la biometría / no biometría",
    exp:"«En caso la reposición la realice un tercero, debe presentar una carta poder legalizada y adicionalmente debe pasar la biometría / no biometría».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Si la línea móvil está bloqueada por robo o pérdida, ¿por qué canal se orienta a recuperar el chip?",
    opciones:["Autogestión: Cajero - ATM","Solo el canal telefónico","Mi Claro App"],
    correcta:"Autogestión: Cajero - ATM",
    exp:"«Si la línea móvil se encuentra bloqueada (Robo, pérdida), orienta al cliente a que recupere su Chip por los canales de Autogestión: Cajero - ATM».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Tras realizar la reposición de chip, ¿qué se le recomienda al cliente?",
    opciones:["Cambiar las contraseñas de sus cuentas de correo y de banca móvil","Comprar un equipo nuevo","Presentar un reclamo por Calidad"],
    correcta:"Cambiar las contraseñas de sus cuentas de correo y de banca móvil",
    exp:"«Recomendar al cliente que luego de realizar la Reposición de Chip, debe realizar el cambio de contraseñas en sus cuentas de correo y Banca móvil».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"¿Cómo se tipifica la atención informativa de Reposición de Chip?",
    opciones:["Información / Información - Información General / Postventa / Reposición de Chip / Equipo","Variación / Estado de Línea / Cliente / Cambio de Plan","INFORMACIÓN / RENTESEG – OSIPTEL"],
    correcta:"Información / Información - Información General / Postventa / Reposición de Chip / Equipo",
    exp:"«Tipificación informativa en SIAC Único: Información / Información - Información General / Postventa / Reposición de Chip / Equipo».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"El cambio de tecnología de 3G a 4G tiene un costo de chip de:",
    opciones:["Sin costo","S/ 5.00","S/ 1.00"],
    correcta:"Sin costo",
    exp:"En la tabla de costo de chip, el «Cambio de Tecnología 3G a 4G» figura como 'Sin costo'.",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Cliente compró el chip 'Activa Tu Claro' y no puede activarlo como chip repuesto. ¿Qué se le indica?",
    opciones:["Que requiere validación biométrica y debe acudir a un Centro de Atención","Que llame nuevamente en 24 horas","Que compre otro chip"],
    correcta:"Que requiere validación biométrica y debe acudir a un Centro de Atención",
    exp:"«Indicarle que requiere de validación biométrica, y que debe acudir a un Centro de Atención».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Como medio de atención para reposición de chip, además de PA/CAV/CAVE, el cliente puede:",
    opciones:["Agendar su cita desde Mi Claro App antes de acudir al CAV","Hacerla 100% por teléfono","Solicitarla por WhatsApp"],
    correcta:"Agendar su cita desde Mi Claro App antes de acudir al CAV",
    exp:"«Medio de atención: PA, CAV, CAVE, CAV's en distribuidores (informa al cliente que puede agendar su cita antes de acudir al CAV, desde Mi Claro App). ATM: Móvil».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"En el flujo Corporativo-Mail de reposición de chip, el asesor mail primero:",
    opciones:["Se contacta por llamada al RRLL para solicitar la autorización de la reposición","Genera el chip de inmediato","Deriva a la tienda"],
    correcta:"Se contacta por llamada al RRLL para solicitar la autorización de la reposición",
    exp:"«Asesor mail se contacta por llamada al RRLL para solicitar la autorización de la reposición de chip».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"En el flujo corporativo, la entrega del chip se realiza:",
    opciones:["Solo a la persona autorizada en la solicitud","A cualquier trabajador de la empresa","Por delivery a la dirección de facturación"],
    correcta:"Solo a la persona autorizada en la solicitud",
    exp:"«Entrega de chip solo se realizará a la persona autorizada en la solicitud».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"En el flujo corporativo, el cliente asigna los chips:",
    opciones:["Vía Mi Claro, con su contraseña única","Llamando al 135","Presencialmente en un CAV"],
    correcta:"Vía Mi Claro, con su contraseña única",
    exp:"«Cliente procede a la asignación de los chip vía Mi Claro con su contraseña única».",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"Antes de ejecutar el bloqueo, ¿qué se valida sobre el equipo a bloquear?",
    opciones:["Que el IMEI, marca y modelo estén asociados a la línea","Que el equipo esté pagado","Que sea un smartphone"],
    correcta:"Que el IMEI, marca y modelo estén asociados a la línea",
    exp:"«Verifica que el IMEI, Marca y Modelo de equipo a bloquear esté asociado a la línea e infórmale la marca y modelo de dicho equipo».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el cliente acepta una suspensión temporal en lugar del bloqueo, el asesor informa que:",
    opciones:["Una vez que se reactive el servicio, la reactivación tiene costo","La suspensión es indefinida","No hay ningún costo"],
    correcta:"Una vez que se reactive el servicio, la reactivación tiene costo",
    exp:"«Si el cliente acepta la solicitud de suspensión temporal, informa que una vez que se reactive el servicio tiene costo».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"¿Cuál de estos tipos de documento NO figura entre los aceptados para validar la identidad en el bloqueo?",
    opciones:["Licencia de conducir","DNI","Carné de Extranjería (CE)"],
    correcta:"Licencia de conducir",
    exp:"Documentos aceptados: DNI, CE, PASAPORTE, CPP, CTTM, CIRE, CIE, RUC. La licencia de conducir no está en la lista.",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Para bloquear MÁS DE UN equipo, el asesor debe:",
    opciones:["Seguir el procedimiento indicado para el bloqueo de más de un equipo (el equipo se bloquea por línea)","Bloquear todos con un solo registro en el ID","Derivar siempre al canal presencial"],
    correcta:"Seguir el procedimiento indicado para el bloqueo de más de un equipo (el equipo se bloquea por línea)",
    exp:"El diagrama contempla el escenario «Si solicita bloquear más de un equipo» con su operativa; el bloqueo se realiza por línea y equipo asociado.",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"El cliente informa que NO reconoce una reposición de chip. El asesor debe:",
    opciones:["Aplicar las validaciones post atención definidas para ese escenario","Ignorar el reclamo","Bloquear la línea de inmediato sin validar"],
    correcta:"Aplicar las validaciones post atención definidas para ese escenario",
    exp:"El diagrama de Reposición de Chip contempla «¿Cliente no reconoce la reposición de chip?» dentro de 'Validaciones post atención'.",
    fuente:"Reposición de Chip Diagrama.xlsm" },

  { q:"En el bloqueo, si el número desde el que llama el cliente NO coincide (sin considerar códigos de ciudad), el asesor:",
    opciones:["Registra el número que figura en los sistemas de Claro","Registra el número que dice el cliente","No registra ningún número"],
    correcta:"Registra el número que figura en los sistemas de Claro",
    exp:"«El número no coincide (sin considerar los códigos de ciudad): se registrará el número que figura en nuestros sistemas».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"Si el cliente NO conoce el número desde el cual está llamando, el asesor:",
    opciones:["Informa que se registrará el número que se visualiza en el sistema","No puede continuar","Registra 000000000"],
    correcta:"Informa que se registrará el número que se visualiza en el sistema",
    exp:"«Opción 3: el cliente no conoce el número del cual está llamando. Informar que se registrará el número que se visualiza en el sistema».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" },

  { q:"En el campo 'N° teléfono llamada entrante' se registra:",
    opciones:["La llamada entrante que muestra GENESYS","El número de referencia del cliente","El IMEI del equipo"],
    correcta:"La llamada entrante que muestra GENESYS",
    exp:"«En este campo registra la llamada entrante que muestra GENESYS».",
    fuente:"Bloqueo de Línea y Equipo Diagrama.xlsm" }

  ]
};
